//How to balance this table
//-------------------------
//The total added weight of all the entries should be (roughly) equal to the total number of lootdrops
//(take in account those that spawn more than one object!)
//
//While this is random, probabilities tells us that item distribution will have a tendency to look like
//the content of the weighted table that created them.
//The less lootdrops, the less even the distribution.
//
//If you want to give items a weight <1 you can multiply all the weights by 10
//
//the "" entry will spawn nothing, if you increase this value,
//ensure that you balance it with more spawn points

//table data:
//-----------
//aft maintenance: 		24 items, 18 spots 2 extra (28/08/2014)
//asmaint: 				16 items, 11 spots 0 extra (08/08/2014)
//asmaint2:			 	36 items, 26 spots 2 extra (28/08/2014)
//fpmaint:				5  items,  4 spots 0 extra (08/08/2014)
//fpmaint2:				12 items, 11 spots 2 extra (28/08/2014)
//fsmaint:				0  items,  0 spots 0 extra (08/08/2014)
//fsmaint2:				40 items, 27 spots 5 extra (28/08/2014)
//maintcentral:			2  items,  2 spots 0 extra (08/08/2014)
//port:					5  items,  5 spots 0 extra (08/08/2014)

GLOBAL_LIST_INIT(maintenance_loot, list(
	/obj/item/bodybag = 1,
	/obj/item/clothing/glasses/meson = 2,
	/obj/item/clothing/glasses/sunglasses = 1,
	/obj/item/clothing/gloves/color/fyellow = 1,
	/obj/item/clothing/head/hardhat = 1,
	/obj/item/clothing/head/hardhat/red = 1,
	/obj/item/clothing/head/that = 1,
	/obj/item/clothing/head/ushanka = 1,
	/obj/item/clothing/head/welding = 1,
	/obj/item/clothing/mask/gas = 15,
	/obj/item/clothing/suit/hazardvest = 1,
	/obj/item/clothing/under/rank/vice = 1,
	/obj/item/assembly/prox_sensor = 4,
	/obj/item/assembly/timer = 3,
	/obj/item/flashlight = 4,
	/obj/item/flashlight/pen = 1,
	/obj/item/flashlight/glowstick/random = 4,
	/obj/item/multitool = 2,
	/obj/item/radio/off = 2,
	/obj/item/t_scanner = 5,
	/obj/item/airlock_painter = 1,
	/obj/item/stack/cable_coil/random = 4,
	/obj/item/stack/cable_coil/random/five = 6,
	/obj/item/stack/medical/bruise_pack = 1,
	/obj/item/stack/rods/ten = 9,
	/obj/item/stack/rods/twentyfive = 1,
	/obj/item/stack/rods/fifty = 1,
	/obj/item/stack/sheet/cardboard = 2,
	/obj/item/stack/sheet/metal/twenty = 1,
	/obj/item/stack/sheet/mineral/plasma = 1,
	/obj/item/stack/sheet/rglass = 1,
	/obj/item/book/manual/wiki/engineering_construction = 1,
	/obj/item/book/manual/wiki/engineering_hacking = 1,
	/obj/item/clothing/head/cone = 1,
	/obj/item/coin/silver = 1,
	/obj/item/coin/twoheaded = 1,
	/obj/item/poster/random_contraband = 1,
	/obj/item/poster/random_official = 1,
	/obj/item/crowbar = 1,
	/obj/item/crowbar/red = 1,
	/obj/item/extinguisher = 11,
	//obj/item/gun/ballistic/revolver/russian = 1, //disabled until lootdrop is a proper world proc.
	/obj/item/hand_labeler = 1,
	/obj/item/paper/crumpled = 1,
	/obj/item/pen = 1,
	/obj/item/reagent_containers/spray/pestspray = 1,
	/obj/item/reagent_containers/glass/rag = 3,
	/obj/item/stock_parts/cell = 3,
	/obj/item/storage/belt/utility = 2,
	/obj/item/storage/box = 2,
	/obj/item/storage/box/cups = 1,
	/obj/item/storage/box/donkpockets = 1,
	/obj/item/storage/box/lights/mixed = 3,
	/obj/item/storage/box/hug/medical = 1,
	/obj/item/storage/fancy/cigarettes/dromedaryco = 1,
	/obj/item/storage/toolbox/mechanical = 1,
	/obj/item/screwdriver = 3,
	/obj/item/tank/internals/emergency_oxygen = 2,
	/obj/item/vending_refill/cola = 1,
	/obj/item/weldingtool = 3,
	/obj/item/wirecutters = 1,
	/obj/item/wrench = 4,
	/obj/item/relic = 3,
	/obj/item/weaponcrafting/receiver = 2,
	/obj/item/clothing/head/cone = 2,
	/obj/item/grenade/smokebomb = 2,
	/obj/item/geiger_counter = 3,
	/obj/item/reagent_containers/food/snacks/grown/citrus/orange = 1,
	/obj/item/radio/headset = 1,
	/obj/item/assembly/infra = 1,
	/obj/item/assembly/igniter = 2,
	/obj/item/assembly/signaler = 2,
	/obj/item/assembly/mousetrap = 2,
	/obj/item/reagent_containers/syringe = 2,
	/obj/item/clothing/gloves/color/random = 8,
	/obj/item/clothing/shoes/laceup = 1,
	/obj/item/storage/secure/briefcase = 3,
	/obj/item/storage/toolbox/artistic = 2,
	/obj/item/toy/eightball = 1,
	"" = 3
	))

GLOBAL_VAR_INIT(trash_list,list(/obj/item/crafting/duct_tape, 
								/obj/item/crafting/wonderglue,
								/obj/item/crafting/turpentine, 
								/obj/item/crafting/abraxo, 
								/obj/item/crafting/reloader,
								/obj/item/crafting/igniter, 
								/obj/item/crafting/timer, 
								/obj/item/crafting/sensor,
								/obj/item/gun/ballistic/automatic/pistol/n99,
								/obj/item/ammo_box/magazine/m10mm_adv, 
								/obj/item/stock_parts/cell, 
								/obj/item/pipe,
								/obj/item/stack/f13Cash/random/bottle_cap/low,
								/obj/item/stack/f13Cash/random/bottle_cap/med,
								/obj/item/stack/f13Cash/random/ncr/med,
								/obj/item/stack/f13Cash/random/denarius/low,
								/obj/item/reagent_containers/food/snacks/f13/bubblegum,
								/obj/item/reagent_containers/food/snacks/f13/bubblegum/large,
								/obj/item/reagent_containers/food/snacks/f13/cram,
								/obj/item/reagent_containers/food/snacks/f13/cram/large,
								/obj/item/reagent_containers/food/snacks/f13/yumyum,
								/obj/item/reagent_containers/food/snacks/f13/fancylads,
								/obj/item/reagent_containers/food/snacks/f13/sugarbombs,
								/obj/item/reagent_containers/food/snacks/f13/crisps,
								/obj/item/reagent_containers/food/snacks/f13/steak,
								/obj/item/reagent_containers/food/snacks/f13/specialapples,
								/obj/item/reagent_containers/food/snacks/f13/dandyapples,
								/obj/item/reagent_containers/food/snacks/f13/blamco,
								/obj/item/reagent_containers/food/snacks/f13/blamco/large,
								/obj/item/reagent_containers/food/snacks/f13/mechanic,
								/obj/item/reagent_containers/food/snacks/f13/instamash,
								/obj/item/reagent_containers/food/snacks/f13/porknbeans,
								/obj/item/reagent_containers/food/snacks/f13/borscht,
								/obj/item/reagent_containers/food/snacks/f13/dog,
								/obj/item/clothing/shoes/f13/tan, 
								/obj/item/clothing/suit/armor/f13/leatherarmor,
								/obj/item/trash/f13/electronic/toaster, 
								/obj/item/radio,
								/obj/item/reagent_containers/glass/bucket, 
								/obj/item/crowbar,
								/obj/item/flashlight, 
								/obj/item/extinguisher,
								/obj/item/multitool, 
								/obj/item/analyzer,
								/obj/item/t_scanner, 
								/obj/item/weldingtool,
								/obj/item/screwdriver, 
								/obj/item/wirecutters,
								/obj/item/wrench, 
								/obj/item/clothing/head/welding,
								/obj/item/stack/cable_coil/random, 
								/obj/item/kitchen/knife,
								/obj/item/kitchen/fork, 
								/obj/item/storage/bag/tray,
								/obj/item/reagent_containers/glass/bowl, 
								/obj/item/reagent_containers/food/drinks/drinkingglass,
								/obj/item/reagent_containers/food/drinks/drinkingglass/shotglass,
								/obj/item/cultivator, 
								/obj/item/shovel, 
								/obj/item/shovel/spade,
								/obj/item/hatchet, 
								/obj/item/scalpel, 
								/obj/item/circular_saw,
								/obj/item/surgicaldrill, 
								/obj/item/retractor, 
								/obj/item/cautery,
								/obj/item/hemostat, 
								/obj/item/reagent_containers/glass/beaker,
								/obj/item/reagent_containers/glass/beaker/large, 
								/obj/item/ammo_casing/shotgun/beanbag,
								/obj/item/ammo_casing/shotgun/rubbershot, 
								/obj/item/ammo_box/c38,
								/obj/item/taperecorder/empty, 
								/obj/item/radio/off,
								/obj/item/light/tube, 
								/obj/item/light/bulb,
								/obj/item/reagent_containers/syringe, 
								/obj/item/restraints/handcuffs,
								/obj/item/ammo_casing/shotgun/buckshot,
								/obj/item/kitchen/knife/butcher, 
								/obj/item/geiger_counter,
								/obj/item/ammo_box/magazine/m10mm_adv, 
								/obj/item/ammo_box/magazine/m10mm_auto,
								/obj/item/crafting/lunchbox, 
								/obj/item/gun/ballistic/automatic/pistol/ninemil,
								/obj/item/ammo_box/magazine/m9mm, 
								/obj/item/gun/ballistic/revolver/colt6250,
								/obj/item/ammo_box/magazine/m556/rifle, 
								/obj/item/ammo_box/magazine/greasegun,
								/obj/item/ammo_box/m44,
								/obj/item/ammo_box/magazine/m45,
								/obj/item/reagent_containers/pill/patch/healingpowder, 
								/obj/item/ammo_box/a762,
								/obj/item/ammo_box/a308, 
								/obj/item/ammo_box/a762/doublestacked,
								/obj/item/ammo_box/c9mm, 
								/obj/item/ammo_box/c10mm,
								/obj/item/ammo_box/a556, 
								/obj/item/ammo_box/c45,
								/obj/item/storage/pill_bottle/chem_tin/mentats, 
								/obj/item/storage/pill_bottle/chem_tin/fixer,
								/obj/item/storage/pill_bottle/chem_tin/radx,
								/obj/item/reagent_containers/food/drinks/bottle/orangejuice, 
								/obj/item/reagent_containers/food/drinks/bottle/cognac,
								/obj/item/reagent_containers/food/drinks/bottle/whiskey, 
								/obj/item/reagent_containers/hypospray/medipen/psycho,
								/obj/item/clothing/glasses/sunglasses/big, 
								/obj/item/clothing/glasses/sunglasses,
								/obj/item/clothing/glasses/material/mining, 
								/obj/item/clothing/glasses/eyepatch,
								/obj/item/clothing/head/helmet/knight/fluff/rider, 
								/obj/item/clothing/shoes/f13/cowboy,
								/obj/item/clothing/shoes/f13/explorer, 
								/obj/item/clothing/shoes/f13/military/diesel,
								/obj/item/clothing/shoes/f13/military/female/diesel, 
								/obj/item/clothing/gloves/f13/leather,
								/obj/item/clothing/gloves/f13/military, 
								/obj/item/clothing/gloves/f13/ncr,
								/obj/item/gun/ballistic/shotgun/boltaction, 
								/obj/item/toy/crayon/spraycan, 
								/obj/item/stock_parts/capacitor/adv,
								/obj/item/stock_parts/scanning_module/adv, 
								/obj/item/stock_parts/manipulator/nano, 
								/obj/item/stock_parts/micro_laser/high,
								/obj/item/stock_parts/matter_bin/adv, 
								/obj/item/stock_parts/manipulator/pico, 
								/obj/item/stock_parts/matter_bin/super
))